### ISSUE TITLE
FTPS not working

### ISSUE THREAD

**Issue by fravia1** [toulousain79/MySB#11]
FTPS is not working , even though ssh is allowed on the user

**Comment by toulousain79** [comment]
Are you sure ? This service works perfectly. Do you have change something about quota?

**Comment by fravia1** [comment]
Well , I did try out few things but except root if any other users which tries to login through putty , putty crashes immediately.

Also the seedbox manager produces wrong configuration files for filezialla because the ftp address  has a : 8889(or some port address which is rutorrent port address hence you have to remove the port number and then use it on filezilla to make it work , an hence the configuration file also has the same error.

Also please don't mind me posting all these issues , I am really grateful for you create this script , I replaced this script for my script .

**Comment by toulousain79** [comment]
SSH connexions for users is not a service provide by MySB. MySB is a fork of Notos script. I have change the method and I have keep some old possibilities like change password by SSH for users. I have only keep this ideas for use by the portal. So the SSH over FTP or FTP over SSL work well but without the SeedboxManager configuration file, I know that. I think to remove it because the first service is to reboot the user rtorrent session, and we can do that with the portal.
