### ISSUE TITLE
No Support For Magnet Links

### ISSUE THREAD

**Issue by betaboy44** [toulousain79/MySB#18]
Adding torrents by magnet links is not supported ?

**Comment by toulousain79** [comment]
Hi,
No, magnet links is not supported.
If I'm not mistaken, magnetic links use the DHT. And by default the DHT is not enabled in the configuration file rTorrent. It seems to me that the DHT does not help to remain anonymous, it is not in the logic of MySB.
Feel free to correct me if I'm wrong.

**Comment by betaboy44** [comment]
Ok nice i understood,..one thing more when ever server gets restarted in which seedbox is installed then after that if we login to rutorrent then it says rutorrent can't be connected :\
After restarting server do we have to enable something again ?

**Comment by toulousain79** [comment]
No, when installation is completely done, the server reboot and you receive a mail. After that, your box is ready. There is no more action to do. You can have a little error when you connect for the first time to ruTorrent, but after a refresh of the page, all is done.
Leave me some minutes to install the v2.1 and check if i get the same problem like you.

**Comment by toulousain79** [comment]
I did a fresh install with all options enabled, and I have no problem with ruTorrent connection problem.
Try restarting your session rTorrent (via Seedbox MySB gold-Manager Portal).

**Comment by betaboy44** [comment]
why there is no speed in torrents ?
there is no upload or download speed :\
And installation is very complex and hard.

**Comment by toulousain79** [comment]
OK, if you want more speed, you must change your blocklist accordingly to your trackers ... Lot of seeders are present in some blocklist, depend trackers you used.
The speed rate work perfectly in ruTorrent. Give me some screenshot and log file if you want help. Otherwise the free criticism serve me for nothing.
Why installation is very complex and hard? You have only one command line to use and some questions to answer. Where are the difficulties?
If MySB does not suit you, so forget it.
